---
# A task to build a Docker image for a Java app with Jib

# Task definition

platform: linux
container_limits: {}

# Use the 'maven:3.6.3' image from Docker Hub
image_resource:
  type: registry-image
  source:
    repository: docker
    tag: latest

# Cache Maven artifacts so we don't download the internet again
# Caches are scoped to a particular task name inside of a pipeline's job.
caches:
  - path: $HOME/.m2/repository

# We will provide an input called 'git' to this Task
# This causes Concourse to git checkout a specific commit.
# It also allows us to execute this step independently, for a specific Git commit.
# However, the parent pipeline only runs this task when the previous 'unit' job has passed.
inputs:
  - name: git

outputs:
  - name: image # Concourse creates this directory for us. This will hold the OCI image .tar

# What do we want this task to do?
# Tell Concourse the commands it should execute, in this Task
# Build an OCI image as a .tar file. Skip unit tests, because we've already run them in the previous Job
#     mvn compile jib:buildTar ... -DskipTests
# ls -l git/;mvn -B -X -f git/pom.xml clean package jib:buildTar -DoutputDirectory=$(pwd)/image/camel-sports-api.tar;ls -l git/target/;
run:
  path: /bin/sh
  args:
  - -c
  - |
    docker build -t camel-sports-api:latest -f git/Dockerfile .;docker images
